### ISSUE TITLE
Does this library overkill if used for android only?

### ISSUE THREAD

**Issue by mochadwi** [badoo/MVIKotlin#166]
This library is awesome, and our team wants to implement this for Android only (maybe for now, hopefully in the long run we're developing for KMM as well)

**Comment by arkivanov** [comment]
Thanks! There is no any additional overhead due to multiplatform compatibility. The core functionality is very tiny and does not depend on any library/framework. You can pick one of the existing extensions (for coroutines or Reaktive) or create your own. Also if you are planning to use it in an existing project, then you can introduce it gradually (e.g. in one of the new features) and check if you like it.

**Comment by arkivanov** [comment]
Also welcome to the Slack channel where you can ask any questions: [#mvikotlin](https://kotlinlang.slack.com/archives/C01403U1ZGW)

**Comment by mochadwi** [comment]
Thanks for the reply, great I'm already joined the slack channel!

Closing this issue now
