### ISSUE TITLE
Best practice: saving Store while configuration changes

### ISSUE THREAD

**Issue by Skeptick** [badoo/MVIKotlin#41]
In the sample application, I did not find an example of how to save the Store and get the result of an asynchronous operation that was started before the configuration change. I would be glad to see your vision for this case.

**Comment by arkivanov** [comment]
Good question! I will cover this in the documentation and in the samples. In short, you should use the [`StateKeeper`](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin/src/commonMain/kotlin/com/arkivanov/mvikotlin/core/utils/statekeeper/StateKeeper.kt), and one of its default containers: 

- [`ParcelableStateKeeperContainer`](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin/src/androidMain/kotlin/com/arkivanov/mvikotlin/core/utils/statekeeper/ParcelableStateKeeperContainerFactory.kt)
- [`SerializableStateKeeperContainer`](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin/src/androidMain/kotlin/com/arkivanov/mvikotlin/core/utils/statekeeper/SerializableStateKeeperContainerFactory.kt)
- [`SimpleStateKeeperContainer`](https://github.com/arkivanov/MVIKotlin/blob/master/mvikotlin/src/commonMain/kotlin/com/arkivanov/mvikotlin/core/utils/statekeeper/SimpleStateKeeperContainerFactory.kt)

If you want async operations to survive configuration changes in Android you should retain your `Stores`. Some possible solutions:
- You can use retained `Fragments` - this in general might be dangerous because of possible memory leaks
- You can retain only `Stores` using `SimpleStateKeeperContainer`

I would recommend the second option. In the sample you can find how `State` is retained:
- [Take initial state from the `StateKeeper`](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-common-internal/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/internal/store/list/TodoListStoreAbstractFactory.kt#L23)
- [Put to `StateKeeper`](https://github.com/arkivanov/MVIKotlin/blob/57348cfd53c791d5f939436a2e8ffdb788509b0f/sample/todo-common-internal/src/commonMain/kotlin/com/arkivanov/mvikotlin/sample/todo/common/internal/store/list/TodoListStoreAbstractFactory.kt#L30)
- [Retain state](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/MainActivity.kt#L38)
- [Restore state](https://github.com/arkivanov/MVIKotlin/blob/master/sample/todo-app-android/src/main/java/com/arkivanov/mvikotlin/sample/todo/android/MainActivity.kt#L45)

Same way you can retain a whole `Store`, not just its state.

**Comment by arkivanov** [comment]
When a `Store` is retained it should not be disposed. I will cover this case in sample.

**Comment by arkivanov** [comment]
The last point (to not dispose the `Store` when it's retained) is actually not so easy. Please consider retained `Fragments` as a solution for now. I will keep this issue open until I find a solution.

**Comment by Skeptick** [comment]
Thanks for the detailed answer! Earlier, I looked at examples and source code and found `ParcelableStateKeeperContainer` very useful for saving state when the Android application process dies :)

Regarding `Store` persistence ... Perhaps some way out of this situation would be to save `Store` in `androidx.lifecycle.ViewModel `and call `dispose` in the `onCleared` method? Although of course, in fact, I would like to avoid this extra "wrapper" 🤔️

**Comment by arkivanov** [comment]
Yes, if you need to persist the state over process death then you you can make your `State` `Parcelable` and use `ParcelableStateKeeperContainer`, or make your `State` `Serializable` and use `SerializableStateKeeperContainer`. The `StateKeeper.register {}` callback is called when it's time to save state. In this callback you can modify the state (by making a copy) before saving, e.g. clear `isLoading` flag or whatever.

But if you need to keep async operations running while configuration change then you can use `SimpleStateKeeperContainer` and save/restore a whole `Store`. The important thing is to **not** dispose the `Store` if it was retained. I already found a solution and will update samples soon.

Regarding `ViewModel`, you can try using it. But looks like using just `SimpleStateKeeperContainer` will be enough (it's already there, no need for an additional dependency). So up to you.

**Comment by arkivanov** [comment]
The solution is on the way! #43
